INSERT INTO `items` (`name`, `label`, `limit`) VALUES
	('corn_seed', 'Corn Seed', 100),
	('corn_raw', 'Raw Corn', 100),
	('corn', 'Corn', 100),
	('tomato_seed', 'Tomato Seed', 100),
	('tomato_raw', 'Raw Tomato', 100),
	('tomato', 'Tomato', 100),
	('wheat_seed', 'Wheat Seed', 100),
	('wheat_raw', 'Raw Wheat', 100),
	('wheat', 'Wheat', 100),
	('broccoli_seed', 'Broccoli Seed', 100),
	('broccoli_raw', 'Raw Broccoli', 100),
	('broccoli', 'Broccoli', 100),
	('carrot_seed', 'Carrot Seed', 100),
	('carrot', 'Carrot', 100),
	('potato_seed', 'Potato Seed', 100),
	('potato_raw', 'Raw Potato', 100),
	('potato', 'Potato', 100),
	('pickle_seed', 'Pickle Seed', 100),
	('pickle_raw', 'Raw Pickle', 100),
	('pickle', 'Pickle', 100),
	('weed_seed', 'Weed Seed', 100),
	('weed_raw', 'Raw Weed', 100),
	('weed', 'Weed', 100),
	('cocaine_seed', 'Cocaine Seed', 100),
	('cocaine_raw', 'Raw Cocaine', 100),
	('cocaine', 'Cocaine', 100),
	('heroin_seed', 'Heroin Seed', 100),
	('heroin_raw', 'Raw Heroin', 100),
	('heroin', 'Heroin', 100),
	('garden_pitcher', 'Garden Pitcher', 1),
	('garden_shovel', 'Garden Shovel', 1)
;