INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('corn_seed', 'Corn Seed', 10),
	('corn_raw', 'Raw Corn', 10),
	('corn', 'Corn', 10),
	('tomato_seed', 'Tomato Seed', 10),
	('tomato_raw', 'Raw Tomato', 10),
	('tomato', 'Tomato', 10),
	('wheat_seed', 'Wheat Seed', 10),
	('wheat_raw', 'Raw Wheat', 10),
	('wheat', 'Wheat', 10),
	('broccoli_seed', 'Broccoli Seed', 10),
	('broccoli_raw', 'Raw Broccoli', 10),
	('broccoli', 'Broccoli', 10),
	('carrot_seed', 'Carrot Seed', 10),
	('carrot', 'Carrot', 10),
	('potato_seed', 'Potato Seed', 10),
	('potato_raw', 'Raw Potato', 10),
	('potato', 'Potato', 10),
	('pickle_seed', 'Pickle Seed', 10),
	('pickle_raw', 'Raw Pickle', 10),
	('pickle', 'Pickle', 10),
	('weed_seed', 'Weed Seed', 10),
	('weed_raw', 'Raw Weed', 10),
	('weed', 'Weed', 10),
	('cocaine_seed', 'Cocaine Seed', 10),
	('cocaine_raw', 'Raw Cocaine', 10),
	('cocaine', 'Cocaine', 10),
	('heroin_seed', 'Heroin Seed', 10),
	('heroin_raw', 'Raw Heroin', 10),
	('heroin', 'Heroin', 10),
	('garden_pitcher', 'Garden Pitcher', 100),
	('garden_shovel', 'Garden Shovel', 100)
;